; test-subanta-base
; testall
(defun test-subanta-base ()
 (let (tests test ans out)
  (setq tests '(
   (nii M ii)
   (nii M ii1)
   (senaanii M ii1)
   (agraNii M ii1)
   (sudhii M ii1)
   (sudhii M ii)
   (dhii F ii1)
   (bhuu F uu1)
   (dos N IRR)
   (aashis F IRR)
   (ap F IRR)
  ))
  (while tests
   (setq test (car tests))
   (setq tests (cdr tests))
   (setq ans (apply 'subanta-base test))
   (setq out (format "(subanta-base %s) => %s\n" test ans))
   (insert out)
  )
 )
)
(defun testall ()
 (test-subanta-base)
)
